version: '3.8'

services:

  talktide-db:
    image: postgres:14.1-alpine
    restart: always
    container_name: chat-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - chat-db-vol:/var/lib/postgresql/data
    networks:
      - chat-net

  talktide-broker:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data-vol:/var/lib/rabbitmq/
        - rabbitmq-log-vol:/var/log/rabbitmq
    networks:
        - chat-net

  talktide-fe:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    container_name: chat-fe
    image: chat-fe:0.0.1
    ports:
      - 4200:80
    networks:
      - chat-net

  talktide-gateway:
    build: 
      context: ../gateway
      dockerfile: Dockerfile
    container_name: chat-gateway
    image: chat-gateway:0.0.1
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - chat-net
    depends_on:
      - talktide-broker
  
  talktide-service-authuser:
    build: 
      context: ../service-authuser
      dockerfile: Dockerfile
    container_name: chat-service-authuser
    env_file:
      - .env
    image: chat-service-authuser:0.0.1
    networks:
      - chat-net
    depends_on:
      - talktide-db
      - talktide-broker

  talktide-service-amessage:
    build: 
      context: ../service-message
      dockerfile: Dockerfile
    container_name: chat-service-message
    env_file:
      - .env
    image: chat-service-message:0.0.1
    networks:
      - chat-net
    depends_on:
      - talktide-db
      - talktide-broker
  
  talktide-socket-server:
    build: 
      context: ../socket-server
      dockerfile: Dockerfile
    container_name: chat-socket
    image: chat-socket:0.0.1
    ports:
      - 8082:8082
    env_file:
      - .env
    networks:
      - chat-net
    depends_on:
      - talktide-broker

volumes:
  chat-db-vol:
  rabbitmq-log-vol:
  rabbitmq-data-vol:

networks:
  chat-net:
    driver: bridge